connector:
    name: oro_importexport
    jobs:
        dmkfeeaccounting:
            title: "Start fee accounting for member billings"
            type: export
            steps:
                # Lesen der Entity, Erstellung der PDFs, Schreiben auf externes Filesystem
                createfee:
                    title:     create member fee
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    dmkclub_member.job.reader.feeaccounting
                        processor: dmkclub_member.job.processor.feeaccounting
                        writer:    dmkclub_member.job.writer.feeaccounting
                    parameters:
                        batch_size: 50

