datagrid:
    dmkclub-members-grid:
        extended_entity_name: "%dmkclub_member.member.entity.class%"
        source:
            type: orm
            acl_resource: dmkclub_member_view
            query:
                select:
                    - m.id
                    - m.memberCode
                    - c.firstName
                    - c.lastName
                    - m.isHonorary
                    - m.isActive
                    - m.status
                    - m.paymentOption
                    - a.city
                    - c.birthday
                    - m.createdAt
                    - m.updatedAt
                from:
                    - { table: "%dmkclub_member.member.entity.class%", alias: m }
                join:
                    left:
                        - { join: m.contact, alias: c }
                        - { join: m.postalAddress, alias: a }
        columns:
            memberCode:
                label:         dmkclub.member.member_code.label
            firstName:
                label:         orocrm.contact.first_name.label
            lastName:
                label:         orocrm.contact.last_name.label
            isHonorary:
                label:         dmkclub.member.is_honorary.label
                frontend_type: boolean
            isActive:
                label:         dmkclub.member.is_active.label
                frontend_type: boolean
            status:
                label:         dmkclub.member.status.label
#                frontend_type: translatable
            paymentOption:
                label:         dmkclub.member.payment_option.label
#                frontend_type: translatable
            city:
                label:         oro.address.city.label
            birthday:
                label:         orocrm.contact.birthday.label
                frontend_type: date
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      dmkclub_member_view
                params:     [ id ]
            update_link:
                type:       url
                route:      dmkclub_member_update
                params:     [ id ]
        sorters:
            columns:
                memberCode:
                    data_name: m.memberCode
                lastName:
                    data_name: c.lastName
                firstName:
                    data_name: c.firstName
                isHonorary:
                    data_name: m.isHonorary
                isActive:
                    data_name: m.isActive
                status:
                    data_name: m.status
                paymentOption:
                    data_name: m.paymentOption
                city:
                    data_name: a.city
                birthday:
                    data_name: c.birthday
                createdAt:
                    data_name: m.createdAt
                updatedAt:
                    data_name: m.updatedAt
            default:
                name:  "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                memberCode:
                    type: string
                    data_name: m.memberCode
                firstName:
                    type: string
                    enabled: false
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                isHonorary:
                    type: string
                    enabled: false
                    data_name: m.isHonorary
                isActive:
                    type: string
                    enabled: false
                    data_name: m.active
                status:
                    type: string
                    data_name: m.status
                city:
                    type: string
                    enabled: false
                    data_name: a.city
                birthday:
                    type:      date
                    data_name: c.birthday
                createdAt:
                    type:      datetime
                    data_name: m.createdAt
                updatedAt:
                    type:      datetime
                    data_name: m.updatedAt
                    enabled: false
            default:
                status: { value: 'active', type: "%oro_filter.form.type.filter.text.class%::TYPE_EQUAL" }
        actions:
            view:
                type: navigate
                acl_resource: dmkclub_member_view
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: dmkclub_member_update
                label: oro.grid.action.update
                icon: edit
                link: update_link

# ###
# MemberBilling base grid
# ###
    dmkclub-memberbillings-grid:
        extended_entity_name: "%dmkclub_member.memberbilling.entity.class%"
        source:
            type: orm
            acl_resource: dmkclub_memberbilling_view
            query:
                select:
                    - mb.id
                    - mb.name
                    - mb.startDate
                    - mb.endDate
                    - mb.createdAt
                    - mb.updatedAt
                from:
                    - { table: "%dmkclub_member.memberbilling.entity.class%", alias: mb }
        columns:
            name:
                label:         dmkclub.member.memberbilling.name.label
            startDate:
                label:         dmkclub.member.memberbilling.start_date.label
                frontend_type: date
            endDate:
                label:         dmkclub.member.memberbilling.end_date.label
                frontend_type: date
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      dmkclub_memberbilling_view
                params:     [ id ]
            update_link:
                type:       url
                route:      dmkclub_memberbilling_update
                params:     [ id ]
        sorters:
            columns:
                name:
                    data_name: mb.name
                startDate:
                    data_name: mb.startDate
                endDate:
                    data_name: mb.endDate
                createdAt:
                    data_name: mb.createdAt
                updatedAt:
                    data_name: mb.updatedAt
            default:
                name:  "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                name:
                    type: string
                    data_name: mb.name
                startDate:
                    type:      date
                    data_name: mb.startDate
                endDate:
                    type:      date
                    data_name: mb.endDate
                createdAt:
                    type:      datetime
                    data_name: mb.createdAt
                updatedAt:
                    type:      datetime
                    data_name: mb.updatedAt
                    enabled: false
            default:
                status: { value: 'active', type: "%oro_filter.form.type.filter.text.class%::TYPE_EQUAL" }
        actions:
            view:
                type: navigate
                acl_resource: dmkclub_memberbilling_view
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: dmkclub_memberbilling_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
                