parameters:
    dmkclub.member.form.type.class: DMKClub\Bundle\MemberBundle\Form\Type\MemberType
    dmkclub.member.form.type.api.class: DMKClub\Bundle\MemberBundle\Form\Type\MemberApiType
    dmkclub.member.form.handler.class: DMKClub\Bundle\MemberBundle\Form\Handler\MemberHandler

    dmkclub.form.type.member_select.class:        DMKClub\Bundle\MemberBundle\Form\Type\MemberSelectType
    dmkclub.form.type.member_status.class:        DMKClub\Bundle\MemberBundle\Form\Type\MemberStatusType

    dmkclub.feecategory.form.type.class: DMKClub\Bundle\MemberBundle\Form\Type\FeeCategoryType
    dmkclub.feecategory.form.handler.class: DMKClub\Bundle\MemberBundle\Form\Handler\FeeCategoryHandler
    dmkclub_member.form.type.feecategory_select.class:  DMKClub\Bundle\MemberBundle\Form\Type\FeeCategorySelectType

services:
    dmkclub.member.form.type:
        class: "%dmkclub.member.form.type.class%"
        tags:
            - { name: form.type, alias: dmkclub_member_member }

    dmkclub.member.form.type.api:
        class: "%dmkclub.member.form.type.api.class%"
        tags:
            - { name: form.type, alias: dmkclub_member_member_api }

    dmkclub.member.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_member_form"
            - "dmkclub_member_member"

    dmkclub.member.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "member"
            - "dmkclub_member_member_api"

    dmkclub.member.form.handler:
        class: "%dmkclub.member.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub.member.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: oro_tag.tag_manager }

    dmkclub.member.form.handler.api:
        class: "%dmkclub.member.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub.member.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"

    dmkclub.form.type.member_select:
        class: "%dmkclub.form.type.member_select.class%"
        tags:
            - { name: form.type, alias: "dmkclub_member_member_select" }

    dmkclub.form.type.member_status:
        class: "%dmkclub.form.type.member_status.class%"
        arguments:
            - "@dmkclub.member.status_provider"
        tags:
            - { name: form.type, alias: dmkclub_memberstatus }
# Fee category forms
    dmkclub.feecategory.form.type:
        class: %dmkclub.feecategory.form.type.class%
        tags:
            - { name: form.type, alias: dmkclub_member_feecategory }

    dmkclub.feecategory.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_feecategory_form"
            - "dmkclub_member_feecategory"
    dmkclub.feecategory.form.handler:
        class: %dmkclub.feecategory.form.handler.class%
        scope: request
        arguments:
            - @dmkclub.feecategory.form
            - @request
            - @doctrine.orm.entity_manager

    # Form SELECT type
    dmkclub_member.form.type.feecategory_select:
        class: %dmkclub_member.form.type.feecategory_select.class%
        tags:
            - { name: form.type, alias: dmkclub_feecategory_select }
