parameters:
    dmkclub_member.member.form.type.class: DMKClub\Bundle\MemberBundle\Form\Type\MemberType
    dmkclub_member.member.form.type.api.class: DMKClub\Bundle\MemberBundle\Form\Type\MemberApiType
    dmkclub_member.member.form.handler.class: DMKClub\Bundle\MemberBundle\Form\Handler\MemberHandler
    dmkclub_member.memberbilling.form.type.class: DMKClub\Bundle\MemberBundle\Form\Type\MemberBillingType
    dmkclub_member.memberbilling.form.handler.class: DMKClub\Bundle\MemberBundle\Form\Handler\MemberBillingHandler

    dmkclub.form.type.member_select.class:        DMKClub\Bundle\MemberBundle\Form\Type\MemberSelectType
    dmkclub.form.type.member_status.class:        DMKClub\Bundle\MemberBundle\Form\Type\MemberStatusType
    dmkclub_member.form.type.accounting_processor_select.class: DMKClub\Bundle\MemberBundle\Form\Type\ProcessorSelectType
    dmkclub_member.form.type.default_processor_settings.class: DMKClub\Bundle\MemberBundle\Form\Type\DefaultProcessorSettingsType
    dmkclub_member.form.type.simple_processor_settings.class: DMKClub\Bundle\MemberBundle\Form\Type\SimpleProcessorSettingsType
    dmkclub_member.form.subscriber.processor_settings.class: DMKClub\Bundle\MemberBundle\Form\EventListener\ProcessorSettingsListener

services:
# ####
# FormTypes
# ####
    dmkclub_member.member.form.type:
        class: "%dmkclub_member.member.form.type.class%"
        arguments:
            - "@translator"
        tags:
            - { name: form.type, alias: dmkclub_member_member }

    dmkclub_member.member.form.type.api:
        class: "%dmkclub_member.member.form.type.api.class%"
        tags:
            - { name: form.type, alias: dmkclub_member_member_api }
    dmkclub_member.memberbilling.form.type:
        class: "%dmkclub_member.memberbilling.form.type.class%"
        calls:
            - [addSubscriber, [@dmkclub_member.form.subscriber.processor_settings]]
        arguments:
            - "@translator"
            - "@dmkclub_member.memberbilling.processorprovider"
        tags:
            - { name: form.type, alias: dmkclub_member_memberbilling }


# ####
# Forms
# ####

    dmkclub_member.member.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_member_form"
            - "dmkclub_member_member"

    dmkclub_member.memberbilling.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_member_memberbilling_form"
            - "dmkclub_member_memberbilling"


    dmkclub_member.member.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "member"
            - "dmkclub_member_member_api"

# ####
# FormHandler
# ####

    dmkclub_member.member.form.handler:
        class: "%dmkclub_member.member.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub_member.member.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: oro_tag.tag_manager }

    dmkclub_member.member.form.handler.api:
        class: "%dmkclub_member.member.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub_member.member.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"

    dmkclub_member.memberbilling.form.handler:
        class: "%dmkclub_member.memberbilling.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub_member.memberbilling.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@dmkclub_member.memberbilling.manager"
        tags:
            - { name: oro_tag.tag_manager }

# ####
# FormWidgets
# ####

    dmkclub.form.type.member_select:
        class: "%dmkclub.form.type.member_select.class%"
        tags:
            - { name: form.type, alias: "dmkclub_member_member_select" }

    dmkclub.form.type.member_status:
        class: "%dmkclub.form.type.member_status.class%"
        arguments:
            - "@dmkclub_member.member.status_provider"
        tags:
            - { name: form.type, alias: dmkclub_memberstatus }
    dmkclub_member.form.type.accounting_processor_select:
        class: "%dmkclub_member.form.type.accounting_processor_select.class%"
        arguments:
            - "@dmkclub_member.memberbilling.processorprovider"
        tags:
            - { name: form.type, alias: "dmkclub_member_accounting_processor_select" }

    # Subforms for accounting processor setting
    dmkclub_member.form.type.default_processor_settings:
        class: "%dmkclub_member.form.type.default_processor_settings.class%"
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: "dmkclub_member_default_processor_settings" }
    dmkclub_member.form.type.simple_processor_settings:
        class: "%dmkclub_member.form.type.simple_processor_settings.class%"
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: "dmkclub_member_simple_processor_settings" }
    # listener to switch settings form for selected processor
    # is injected to dmkclub_member.memberbilling.form.type
    dmkclub_member.form.subscriber.processor_settings:
        class: %dmkclub_member.form.subscriber.processor_settings.class%
        arguments:
            - "@dmkclub_member.memberbilling.processorprovider"
            - "@oro_entity.doctrine_helper"
