aliases:
   oro/datagrid/action/dmksendmemberfee-mass-action$: dmkclubmember/js/datagrid/action/dmksendmemberfee-mass-action
   oro/datagrid/action/mark-feecorrection-mass-action$: dmkclubmember/js/datagrid/action/mark-feecorrection-mass-action
dynamic-imports:
   dmkclubmember:
      - dmkclubmember/js/app/views/board/proposal-card-view
      - oro/datagrid/action/dmksendmemberfee-mass-action
      - oro/datagrid/action/mark-feecorrection-mass-action
