
services:
    dmkclub_member.datagrid.mass_action.mark_fee_correction:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: markfeecorrection }

    dmkclub_member.datagrid.mass_action.unmark_fee_correction:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionUnmarkAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: unmarkfeecorrection }

    dmkclub_member.datagrid.mass_action.mark_fee_correction_handler:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionHandler
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
            - "@security.authorization_checker"
            - "@dmkclub_member.memberfee.manager"
            - "@logger"

    dmkclub_member.datagrid.mass_action.send_memberfee:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\SendMemberFeeAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmksendmemberfee }

    dmkclub_member.datagrid.mass_action.send_memberfee_handler:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\SendMemberFeeHandler
        public: true
        arguments:
            - "@translator"
            - "@security.authorization_checker"
            - "@dmkclub_member.memberfee.manager"
            - "@dmkclub_member.mailer.processor"
            - "@oro_cron.async.command_runner"
            - "@logger"
