
services:
    DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: markfeecorrection }

    DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionUnmarkAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: unmarkfeecorrection }

    dmkclub_member.datagrid.mass_action.mark_fee_correction_handler:
        class: DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\MemberFeeCorrectionHandler
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
            - "@security.authorization_checker"
            - "@dmkclub_member.memberfee.manager"
            - "@logger"

    DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\SendMemberFeeAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmksendmemberfee }

    DMKClub\Bundle\MemberBundle\DataGrid\Extension\MassAction\SendMemberFeeHandler:
        public: true
        arguments:
            - "@translator"
            - "@security.authorization_checker"
            - "@dmkclub_member.memberfee.manager"
            - '@DMKClub\Bundle\MemberBundle\Mailer\Processor'
            - "@oro_cron.async.command_runner"
            - "@logger"
