oro_menu_config:
    items:
        dmkclub_member:
            label:   'dmkclub.member.entity_plural_label'
            route:   'dmkclub_member_index'
            display: false
            extras:
                routes:      ['/^dmkclub_member_(index|view)$/']
                position:    210
                description: 'dmkclub.member.entity_plural_label'
        dmkclub_memberbilling:
            label:   'dmkclub.member.memberbilling.entity_plural_label'
            route:   'dmkclub_memberbilling_index'
            display: false
            extras:
                routes:      ['/^dmkclub_memberbilling_(index|view)$/']
                position:    100
                description: 'dmkclub.member.memberbilling.entity_plural_label'

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        dmkclub_member: ~
                accounting_tab:
                    children:
                        dmkclub_memberbilling: ~

oro_titles:
    dmkclub_member_index: ~
    dmkclub_member_view:  "%%member.name%%"
    dmkclub_member_update:  "%%member.name%% - Edit"
    dmkclub_memberbilling_index: ~
    dmkclub_memberbilling_view:  "%%memberbilling.name%%"
    dmkclub_memberbilling_update: '%%memberbilling.name%% - Edit'
    