placeholders:
    # Anzeige des Mitglieds im Account, wird per Konvention gefunden
    orocrm_account_channel_info_member:
        items:
            dmkclub_member_channel_info: ~
    # Link auf Member in Contact-View
    view_navButtons_before:
        items:
            dmkclub_member_linkcontact2member_button:
                order: 10
items:
    dmkclub_member_channel_info:
        action: DMKClubMemberBundle:Member:accountMemberInfo
    dmkclub_member_linkcontact2member_button:
        template: DMKClubMemberBundle:actions:linkContact2MemberButton.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_contact.entity.class%)"
