config:
    paths:
        # Der Key wird in der URI verwendet und auf die Datei in Value gerouted
        'oro/datagrid/action/mark-feecorrection-mass-action': 'bundles/dmkclubmember/js/datagrid/action/mark-feecorrection-mass-action.js'
        'dmkclubmember/js/app/views/board/proposal-card-view': 'bundles/dmkclubmember/js/app/views/board/proposal-card-view.js'
        