DMKClub\Bundle\MemberBundle\Entity\Member:
    alias:                          dmkclub_member
    label:                          dmkclub.member.entity_plural_label
    title_fields:                   [firstName, lastName]
    route:
        name:                       dmkclub_member_view
        parameters:
            id:                     id
    search_template:                DMKClubMemberBundle:Member:searchResult.html.twig
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
        -
            name:                   member_code
            target_type:            text
            target_fields:          [nameCode]
        -
            name:                  dataChannel
            relation_type:         many-to-one
            relation_fields:
                -
                    name:          id
                    target_type:   integer
                    target_fields: [dataChannelId]
DMKClub\Bundle\MemberBundle\Entity\FeeCategory:
    alias: dmkclub_feecategory
    label: dmkclub.feecategory.entity_plural_label
    route:
        name: dmkclub_feecategory_view
        parameters:
            id: id
    search_template: DMKClubMemberBundle:FeeCategory:searchResult.html.twig
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
