parameters:
    dmkclub_member.member.entity.class:                    DMKClub\Bundle\MemberBundle\Entity\Member
    dmkclub_member.member.manager.class:                   DMKClub\Bundle\MemberBundle\Entity\Manager\MemberManager
    dmkclub_member.memberbilling.manager.class:            DMKClub\Bundle\MemberBundle\Entity\Manager\MemberBillingManager
    dmkclub_member.memberfee.manager.class:                DMKClub\Bundle\MemberBundle\Entity\Manager\MemberFeeManager

    dmkclub_member.memberfeediscount.manager.api.class:    Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    dmkclub_member.memberfee.manager.api.class:            Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    dmkclub_member.memberproposal.entity.class:            DMKClub\Bundle\MemberBundle\Entity\MemberProposal

    dmkclub_member.mailer.processor.class:                 DMKClub\Bundle\MemberBundle\Mailer\Processor
#    dmk_club_member.example.class: DMKClub\Bundle\MemberBundle\Example
    # datagrid helpers
    dmkclub_member.country.datagrid_helper.class:          Oro\Bundle\AddressBundle\Datagrid\CountryDatagridHelper
    dmkclub_member.member.status_provider.class:           DMKClub\Bundle\MemberBundle\Provider\MemberStatusProvider
    dmkclub_member.member.twig.class:                      DMKClub\Bundle\MemberBundle\Twig\MemberExtension

    dmkclub_member.memberbilling.entity.class:             DMKClub\Bundle\MemberBundle\Entity\MemberBilling
    dmkclub_member.memberfee.entity.class:                 DMKClub\Bundle\MemberBundle\Entity\MemberFee
    dmkclub_member.memberfeediscount.entity.class:         DMKClub\Bundle\MemberBundle\Entity\MemberFeeDiscount

    dmkclub_member.memberbilling.processorprovider.class:  DMKClub\Bundle\MemberBundle\Accounting\ProcessorProvider
    dmkclub_member.memberbilling.processor_default.class:  DMKClub\Bundle\MemberBundle\Accounting\DefaultProcessor
    dmkclub_member.memberbilling.processor_simple.class:   DMKClub\Bundle\MemberBundle\Accounting\SimpleProcessor

    dmkclub_member.memberfee.pdf.simplegenerator.class:    DMKClub\Bundle\MemberBundle\Accounting\PDF\SimpleMemberFeePdf

    dmkclub_member.memberfee.form.entity_field.handler.class: DMKClub\Bundle\MemberBundle\Form\EntityField\Handler\MemberFeeHandler

services:
    dmkclub_member.memberbilling.manager:
        class:     "%dmkclub_member.memberbilling.manager.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@dmkclub_member.memberbilling.processorprovider"
            - "@oro_segment.segment_manager"
            - "@oro_message_queue.message_producer"
    dmkclub_member.member.manager:
        class:     "%dmkclub_member.member.manager.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    dmkclub_member.memberfee.manager:
        class:     "%dmkclub_member.memberfee.manager.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    dmkclub_member.memberfeediscount.manager.api:
        class: "%dmkclub_member.memberfeediscount.manager.api.class%"
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfeediscount.entity.class%"
            - "@doctrine.orm.entity_manager"
    dmkclub_member.memberfee.manager.api:
        class: "%dmkclub_member.memberfee.manager.api.class%"
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfee.entity.class%"
            - "@doctrine.orm.entity_manager"


    dmkclub_member.memberbilling.processorprovider:
        class: "%dmkclub_member.memberbilling.processorprovider.class%"

    dmkclub_member.mailer.processor:
        class: "%dmkclub_member.mailer.processor.class%"
        arguments:
            - '@doctrine'
            - '@oro_config.global'
            - '@oro_email.email_renderer'
            - '@oro_email.email_holder_helper'
            - '@oro_email.mailer.processor'
#            - '@oro_email.direct_mailer'
            - '@dmkclub_basics.pdf.manager'

    # Wird das verwendet??
    dmkclub_member.country.datagrid_helper:
        class: "%dmkclub_member.country.datagrid_helper.class%"

    dmkclub_member.member.status_provider:
        class: "%dmkclub_member.member.status_provider.class%"
        arguments:
            - "@translator"
    dmkclub_member.member.twig.extension:
        class:                        "%dmkclub_member.member.twig.class%"
        arguments:
            - "@dmkclub_member.member.status_provider"
            - "@dmkclub_member.member.manager"
        tags:
            - { name: twig.extension }

    dmkclub_member.memberbilling.processor.default:
        class: "%dmkclub_member.memberbilling.processor_default.class%"
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: dmkclub_member.billingprocessor }
    dmkclub_member.memberbilling.processor.simple:
        class: "%dmkclub_member.memberbilling.processor_simple.class%"
        tags:
            - { name: dmkclub_member.billingprocessor }


    dmkclub_member.memberfee.pdf.simplegenerator:
        class: "%dmkclub_member.memberfee.pdf.simplegenerator.class%"
        arguments:
            - "@white_october.tcpdf"
            - "@translator"
            - "@twig"
        tags:
            - { name: dmkclub_basics.pdfgenerator }

######################
    dmkclub_member.memberfee.form.entity_field.handler:
        class: "%dmkclub_member.memberfee.form.entity_field.handler.class%"
#        arguments:
#            - "@twig"
        tags:
            - { name: oro_entity.form.entity_field.handler }

### Job Services
    dmkclub_member.async.accounting.feesprocessor:
        class: 'DMKClub\Bundle\MemberBundle\Async\Accounting\FeesMessageProcessor'
        arguments:
            - "@oro_message_queue.message_producer"
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.job.dependent_job_service'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
    dmkclub_member.async.accounting.feeprocessor:
        class: 'DMKClub\Bundle\MemberBundle\Async\Accounting\FeeMessageProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - "@doctrine.orm.entity_manager"
            - "@dmkclub_member.memberbilling.manager"
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
    dmkclub_member.async.accounting.summaryprocessor:
        class: 'DMKClub\Bundle\MemberBundle\Async\Accounting\BillingSummaryMessageProcessor'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dmkclub_member.memberbilling.manager"
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    dmkclub_member.provider.member_entity_name_provider:
        class: DMKClub\Bundle\MemberBundle\Provider\MemberEntityNameProvider
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 100 }
    dmkclub_member.provider.member_fee_entity_name_provider:
        class: DMKClub\Bundle\MemberBundle\Provider\MemberFeeEntityNameProvider
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 100 }

    dmkclub_member.eventlistener.add_member_email_context:
        class: 'DMKClub\Bundle\MemberBundle\EventListener\AddMember2EmailContextListener'
        arguments:
            - '@oro_email.email.activity.manager'
            - '@dmkclub_member.member.manager'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: oro_activity.add_activity, method: addMember2EmailContext }
