parameters:
    dmkclub_member.member.entity.class:                    DMKClub\Bundle\MemberBundle\Entity\Member
    dmkclub_member.memberbilling.manager.class:            DMKClub\Bundle\MemberBundle\Entity\Manager\MemberBillingManager

    dmkclub_member.memberfeediscount.manager.api.class:    Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    dmkclub_member.memberfee.manager.api.class:            Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

#    dmk_club_member.example.class: DMKClub\Bundle\MemberBundle\Example
    # datagrid helpers
    dmkclub_member.country.datagrid_helper.class:          Oro\Bundle\AddressBundle\Datagrid\CountryDatagridHelper
    dmkclub_member.member.status_provider.class:           DMKClub\Bundle\MemberBundle\Provider\MemberStatusProvider
    dmkclub_member.member.twig.class:                      DMKClub\Bundle\MemberBundle\Twig\MemberExtension

    dmkclub_member.memberbilling.entity.class:             DMKClub\Bundle\MemberBundle\Entity\MemberBilling
    dmkclub_member.memberfee.entity.class:                 DMKClub\Bundle\MemberBundle\Entity\MemberFee
    dmkclub_member.memberfeediscount.entity.class:         DMKClub\Bundle\MemberBundle\Entity\MemberFeeDiscount

    dmkclub_member.memberbilling.processorprovider.class:  DMKClub\Bundle\MemberBundle\Accounting\ProcessorProvider
    dmkclub_member.memberbilling.processor_default.class:  DMKClub\Bundle\MemberBundle\Accounting\DefaultProcessor
    dmkclub_member.memberbilling.processor_simple.class:   DMKClub\Bundle\MemberBundle\Accounting\SimpleProcessor

services:
    dmkclub_member.memberbilling.manager:
        class:                        "%dmkclub_member.memberbilling.manager.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@dmkclub_member.memberbilling.processorprovider"
            - "@oro_segment.query.dynamic_segment.query_builder"
            - "@oro_segment.query.static_segment.query_builder"

    dmkclub_member.memberfeediscount.manager.api:
        class: "%dmkclub_member.memberfeediscount.manager.api.class%"
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfeediscount.entity.class%"
            - "@doctrine.orm.entity_manager"
    dmkclub_member.memberfee.manager.api:
        class: "%dmkclub_member.memberfee.manager.api.class%"
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfee.entity.class%"
            - "@doctrine.orm.entity_manager"


    dmkclub_member.memberbilling.processorprovider:
        class: "%dmkclub_member.memberbilling.processorprovider.class%"

    # Wird das verwendet??
    dmkclub_member.country.datagrid_helper:
        class: "%dmkclub_member.country.datagrid_helper.class%"

    dmkclub_member.member.status_provider:
        class: "%dmkclub_member.member.status_provider.class%"
        arguments:
            - "@translator"
    dmkclub_member.member.twig.extension:
        class:                        "%dmkclub_member.member.twig.class%"
        arguments:                    ["@dmkclub_member.member.status_provider"]
        tags:
            - { name: twig.extension }

    dmkclub_member.memberbilling.processor.default:
        class: "%dmkclub_member.memberbilling.processor_default.class%"
        arguments:
            - "@logger"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: dmkclub_member.billingprocessor }
    dmkclub_member.memberbilling.processor.simple:
        class: "%dmkclub_member.memberbilling.processor_simple.class%"
        tags:
            - { name: dmkclub_member.billingprocessor }

