parameters:
    dmkclub_member.member.entity.class:                    DMKClub\Bundle\MemberBundle\Entity\Member

    dmkclub_member.memberproposal.entity.class:            DMKClub\Bundle\MemberBundle\Entity\MemberProposal

#    dmk_club_member.example.class: DMKClub\Bundle\MemberBundle\Example
    # datagrid helpers
    dmkclub_member.country.datagrid_helper.class:          Oro\Bundle\AddressBundle\Datagrid\CountryDatagridHelper
    dmkclub_member.member.status_provider.class:           DMKClub\Bundle\MemberBundle\Provider\MemberStatusProvider

    dmkclub_member.memberbilling.entity.class:             DMKClub\Bundle\MemberBundle\Entity\MemberBilling
    dmkclub_member.memberfee.entity.class:                 DMKClub\Bundle\MemberBundle\Entity\MemberFee
    dmkclub_member.memberfeediscount.entity.class:         DMKClub\Bundle\MemberBundle\Entity\MemberFeeDiscount

    dmkclub_member.memberfee.pdf.simplegenerator.class:    DMKClub\Bundle\MemberBundle\Accounting\PDF\SimpleMemberFeePdf

    dmkclub_member.memberfee.form.entity_field.handler.class: DMKClub\Bundle\MemberBundle\Form\EntityField\Handler\MemberFeeHandler

services:

    DMKClub\Bundle\MemberBundle\Entity\Manager\MemberBillingManager:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - '@DMKClub\Bundle\MemberBundle\Accounting\ProcessorProvider'
            - "@oro_segment.segment_manager"
            - "@oro_message_queue.message_producer"
    DMKClub\Bundle\MemberBundle\Entity\Manager\MemberManager:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    DMKClub\Bundle\MemberBundle\Entity\Manager\MemberFeeManager:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
        
    dmkclub_member.memberfeediscount.manager.api:
        public: true
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfeediscount.entity.class%"
            - "@doctrine.orm.entity_manager"
    dmkclub_member.memberfee.manager.api:
        public: true
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub_member.memberfee.entity.class%"
            - "@doctrine.orm.entity_manager"

    DMKClub\Bundle\MemberBundle\Mailer\Processor:
        public: true
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
            - '@oro_config.global'
            - '@oro_email.email_renderer'
            - '@oro_email.email_holder_helper'
            - '@oro_email.mailer.processor'
#            - '@oro_email.direct_mailer'
            - '@DMKClub\Bundle\BasicsBundle\PDF\Manager'

    # Wird das verwendet??
    dmkclub_member.country.datagrid_helper:
        class: "%dmkclub_member.country.datagrid_helper.class%"

    dmkclub_member.member.status_provider:
        class: "%dmkclub_member.member.status_provider.class%"
        public: true
        arguments:
            - "@translator"

    dmkclub_member.memberfee.pdf.simplegenerator:
        class: "%dmkclub_member.memberfee.pdf.simplegenerator.class%"
        arguments:
            - "@white_october.tcpdf"
            - "@translator"
            - "@twig"
        tags:
            - { name: dmkclub_basics.pdfgenerator }

######################
    dmkclub_member.memberfee.form.entity_field.handler:
        class: "%dmkclub_member.memberfee.form.entity_field.handler.class%"
#        arguments:
#            - "@twig"
        tags:
            - { name: oro_entity.form.entity_field.handler }

### Job Services
    dmkclub_member.async.accounting.feesprocessor:
        class: 'DMKClub\Bundle\MemberBundle\Async\Accounting\FeesMessageProcessor'
        arguments:
            - "@oro_message_queue.message_producer"
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.job.dependent_job_service'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
    dmkclub_member.async.accounting.feeprocessor:
        class: 'DMKClub\Bundle\MemberBundle\Async\Accounting\FeeMessageProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - "@doctrine.orm.entity_manager"
            - '@DMKClub\Bundle\MemberBundle\Entity\Manager\MemberBillingManager'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    DMKClub\Bundle\MemberBundle\Async\Accounting\BillingSummaryMessageProcessor:
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@DMKClub\Bundle\MemberBundle\Entity\Manager\MemberBillingManager'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    DMKClub\Bundle\MemberBundle\Provider\MemberEntityNameProvider:
        class: 
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 100 }

    DMKClub\Bundle\MemberBundle\Provider\MemberFeeEntityNameProvider:
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 100 }

    DMKClub\Bundle\MemberBundle\EventListener\AddMember2EmailContextListener:
        arguments:
            - '@oro_email.email.activity.manager'
            - '@DMKClub\Bundle\MemberBundle\Entity\Manager\MemberManager'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: oro_activity.add_activity, method: addMember2EmailContext }

    DMKClub\Bundle\MemberBundle\EventListener\MemberChangeListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

