parameters:
    dmkclub.member.entity.class:                    DMKClub\Bundle\MemberBundle\Entity\Member
    dmkclub.feecategory.entity.class:       DMKClub\Bundle\MemberBundle\Entity\FeeCategory
#    dmk_club_member.example.class: DMKClub\Bundle\MemberBundle\Example
    # datagrid helpers
    dmkclub.country.datagrid_helper.class:          Oro\Bundle\AddressBundle\Datagrid\CountryDatagridHelper
    dmkclub.member.status_provider.class:           DMKClub\Bundle\MemberBundle\Provider\MemberStatusProvider
    dmkclub.member.twig.class:                      DMKClub\Bundle\MemberBundle\Twig\MemberExtension

services:
#    dmk_club_member.example:
#        class: %dmk_club_member.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    dmkclub.country.datagrid_helper:
        class: "%dmkclub.country.datagrid_helper.class%"

    dmkclub.member.status_provider:
        class: "%dmkclub.member.status_provider.class%"
        arguments:
            - "@translator"
    dmkclub.member.twig.extension:
        class:                        "%dmkclub.member.twig.class%"
        arguments:                    ["@dmkclub.member.status_provider"]
        tags:
            - { name: twig.extension }

    dmkclub_member.form.autocomplete.feecategory.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %dmkclub.feecategory.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: feecategories, acl_resource: dmkclub_feecategory_view }
