services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false 

    DMKClub\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,DependencyInjection,Resources,Tests,DMKClubPaymentBundle.php}'

