services:
    _defaults:
        public: true

    DMKClub\Bundle\PaymentBundle\Controller\SepaCreditorController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'dmkclub_payment.sepacreditor.form' }

