services:
# ####
# FormTypes
# ####

    dmkclub.form.type.payment_options:
        class: DMKClub\Bundle\PaymentBundle\Form\Type\PaymentOptionsType
        arguments:
            - "@dmkclub.payment.options_provider"
        tags:
            - { name: form.type, alias: dmkclub_paymentoptions }

    dmkclub.form.type.payment_intervals:
        class: DMKClub\Bundle\PaymentBundle\Form\Type\PaymentIntervalsType
        arguments:
            - "@dmkclub.payment.intervals_provider"
        tags:
            - { name: form.type, alias: dmkclub_paymentintervals }

    # Bankaccount form type
    dmkclub_payment.form.type.bank_account:
        class: DMKClub\Bundle\PaymentBundle\Form\Type\BankAccountType
        tags:
             - { name: form.type, alias: dmkclub_bankaccount }
    # sepaCreditor form type
    dmkclub_payment.form.type.sepa_creditor:
        class: DMKClub\Bundle\PaymentBundle\Form\Type\SepaCreditorType
        tags:
             - { name: form.type, alias: dmkclub_sepacreditor }


# ####
# Forms
# ####

    # Bankaccount form
    dmkclub_payment.bank_account.form:
        class:           Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_bankaccount"
            - DMKClub\Bundle\PaymentBundle\Form\Type\BankAccountType
            - null
    # SepaCreditor form
    dmkclub_payment.sepacreditor.form:
        class:           Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_sepacreditor"
            - DMKClub\Bundle\PaymentBundle\Form\Type\SepaCreditorType
            - null

# ####
# FormHandler
# ####

    # BankAccount form handler
    DMKClub\Bundle\PaymentBundle\Form\Handler\BankAccount:
        public: true
        arguments:
            - "@dmkclub_payment.bank_account.form"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"


    # SepaCreditor form handler
    DMKClub\Bundle\PaymentBundle\Form\Handler\SepaCreditorHandler:
        public: true
        arguments:
            - "@dmkclub_payment.sepacreditor.form"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

# ####
# FormWidgets
# ####

    # Form SELECT type
    dmkclub_payment.form.type.sepacreditor_select:
        class: DMKClub\Bundle\PaymentBundle\Form\Type\SepaCreditorSelectType
        tags:
            - { name: form.type, alias: dmkclub_sepacreditor_select }
