aliases:
   oro/datagrid/action/dmksepadebitxml-mass-action$: dmkclubpayment/js/datagrid/action/dmksepadebitxml-mass-action
dynamic-imports:
   dmkclubpayment:
      - oro/datagrid/action/dmksepadebitxml-mass-action
