oro_menu_config:
    items:
        accounting_tab:
            label: 'accounting'
            uri: '#'
            display: false
            extras:
                icon: icon-money
                position: 11
