parameters:
    dmkclub.payment.options_provider.class:           DMKClub\Bundle\PaymentBundle\Provider\PaymentOptionsProvider
    dmkclub.payment.twig.class:                       DMKClub\Bundle\PaymentBundle\Twig\PaymentExtension
    dmkclub.payment.sepa.direct_debit_builder.class:  DMKClub\Bundle\PaymentBundle\Sepa\DirectDebitBuilder

services:
    dmkclub.payment.options_provider:
        class: "%dmkclub.payment.options_provider.class%"
        arguments:
            - "@translator"
    dmkclub.payment.twig.extension:
        class:                        "%dmkclub.payment.twig.class%"
        arguments:                    ["@dmkclub.payment.options_provider"]
        tags:
            - { name: twig.extension }

    dmkclub.payment.sepa.direct_debit_builder:
        class: "%dmkclub.payment.sepa.direct_debit_builder.class%"
            