parameters:
    dmkclub.payment.options_provider.class:           DMKClub\Bundle\PaymentBundle\Provider\PaymentOptionsProvider
    dmkclub.payment.intervals_provider.class:         DMKClub\Bundle\PaymentBundle\Provider\PaymentIntervalsProvider
    dmkclub.payment.sepacreditor.entity.class:        DMKClub\Bundle\PaymentBundle\Entity\SepaCreditor
    dmkclub.payment.bankaccount.entity.class:         DMKClub\Bundle\PaymentBundle\Entity\BankAccount
    dmkclub.payment.sepacreditor.manager.api.class:   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    dmkclub.payment.options_provider:
        class: "%dmkclub.payment.options_provider.class%"
        arguments:
            - "@translator"
    dmkclub.payment.intervals_provider:
        class: "%dmkclub.payment.intervals_provider.class%"
        arguments:
            - "@translator"

    dmkclub.payment.sepa.iban.openiban:
        class: 'DMKClub\Bundle\PaymentBundle\Sepa\Iban\OpenIBAN'
        arguments:
            - '@oro_config.user'


    dmkclub.payment.form.autocomplete.sepacreditor.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%dmkclub.payment.sepacreditor.entity.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: dmkclub_sepacreditors, acl_resource: dmkclub_sepacreditor_view }

    dmkclub.payment.sepacreditor.manager.api:
        class: "%dmkclub.payment.sepacreditor.manager.api.class%"
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - "%dmkclub.payment.sepacreditor.entity.class%"
            - "@doctrine.orm.entity_manager"
