connector:
    name: oro_importexport
    jobs:
        dmkexportpdf:
            title: "Export PDF files to external filesystem"
            type: export
            steps:
                # Lesen der Entity, Erstellung der PDFs, Schreiben auf externes Filesystem
                createpdf:
                    title:     create pdf
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    dmkclub_basics.job.reader.pdf
                        processor: dmkclub_basics.job.processor.pdf
                        writer:    dmkclub_basics.job.writer.pdf
                    parameters:
                        batch_size: 50

