services:
    _defaults:
        public: true

    DMKClub\Bundle\BasicsBundle\Controller\ExportController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    DMKClub\Bundle\BasicsBundle\Controller\TwigTemplateController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'dmkclub_basics.twigtemplate.form' }
            