services:
# ####
# FormTypes
# ####
    dmkclub_basics.twigtemplate.form.type:
        class: DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateType
        arguments:
            - "@translator"
            - '@DMKClub\Bundle\BasicsBundle\PDF\Manager'
        tags:
            - { name: form.type, alias: dmkclub_basics_twigtemplate }
# ####
# Forms
# ####
    dmkclub_basics.twigtemplate.form:
        class: Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_basics_twigtemplate"
            - DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateType
            - null
# ####
# FormHandler
# ####
    DMKClub\Bundle\BasicsBundle\Form\Handler\TwigTemplateHandler:
        public: true
        arguments:
            - "@dmkclub_basics.twigtemplate.form"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

# ####
# FormWidgets
# ####

    dmkclub_basics.form.type.twigtemplate_select:
        class: DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateSelectType
        tags:
            - { name: form.type, alias: "dmkclub_basics_twigtemplate_select" }
