parameters:
    dmkclub_basics.twigtemplate.form.type.class: DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateType
    dmkclub_basics.twigtemplate.form.handler.class: DMKClub\Bundle\BasicsBundle\Form\Handler\TwigTemplateHandler
services:
# ####
# FormTypes
# ####
    dmkclub_basics.twigtemplate.form.type:
        class: "%dmkclub_basics.twigtemplate.form.type.class%"
        arguments:
            - "@translator"
        tags:
            - { name: form.type, alias: dmkclub_basics_twigtemplate }
# ####
# Forms
# ####
    dmkclub_basics.twigtemplate.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_basics_twigtemplate_form"
            - "dmkclub_basics_twigtemplate"
# ####
# FormHandler
# ####
    dmkclub_basics.twigtemplate.form.handler:
        class: "%dmkclub_basics.twigtemplate.form.handler.class%"
        scope: request
        arguments:
            - "@dmkclub_basics.twigtemplate.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
