parameters:
    dmkclub_basics.form.type.twigtemplate.class:        DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateType
    dmkclub_basics.form.type.twigtemplate_select.class: DMKClub\Bundle\BasicsBundle\Form\Type\TwigTemplateSelectType
    dmkclub_basics.form.twigtemplate.handler.class:     DMKClub\Bundle\BasicsBundle\Form\Handler\TwigTemplateHandler
services:
# ####
# FormTypes
# ####
    dmkclub_basics.twigtemplate.form.type:
        class: "%dmkclub_basics.form.type.twigtemplate.class%"
        arguments:
            - "@translator"
            - "@dmkclub_basics.pdf.manager"
        tags:
            - { name: form.type, alias: dmkclub_basics_twigtemplate }
# ####
# Forms
# ####
    dmkclub_basics.twigtemplate.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "dmkclub_basics_twigtemplate_form"
            - "dmkclub_basics_twigtemplate"
# ####
# FormHandler
# ####
    dmkclub_basics.twigtemplate.form.handler:
        class: "%dmkclub_basics.form.twigtemplate.handler.class%"
        scope: request
        arguments:
            - "@dmkclub_basics.twigtemplate.form"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

# ####
# FormWidgets
# ####

    dmkclub_basics.form.type.twigtemplate_select:
        class: "%dmkclub_basics.form.type.twigtemplate_select.class%"
        tags:
            - { name: form.type, alias: "dmkclub_basics_twigtemplate_select" }
