parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false 

    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\ExportPdfAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmkexportpdf }
    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\ExportPdfHandler:
        public: true
        arguments:
            - "@translator"
            - "@logger"
            - '@oro_message_queue.message_producer'
            - "@dmkclub_member.memberfee.manager"

    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\DownloadPdfAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmkdownloadpdf }
    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\DownloadPdfHandler:
        public: true
