parameters:
    dmkclub_basics.twigtemplate.entity.class:    DMKClub\Bundle\BasicsBundle\Entity\TwigTemplate
#    dmkclub_basics.twigtemplate.manager.class:   DMKClub\Bundle\BasicsBundle\Entity\Manager\TwigTemplateManager
    dmkclub_basics.provider.privilege_category_provider.class: DMKClub\Bundle\BasicsBundle\Provider\PrivilegeCategoryProvider
    dmkclub_basics.utility.datagrids.class:      DMKClub\Bundle\BasicsBundle\Utility\Datagrids

services:

    dmkclub_basics.pdf.file_manager:
        class: 'DMKClub\Bundle\BasicsBundle\PDF\FileManager'
        arguments:
          - '@knp_gaufrette.filesystem_map'
          - 'dmkclub_pdfexport'

    DMKClub\Bundle\BasicsBundle\PDF\Manager:
        public: true
        arguments:
            - "@white_october.tcpdf"
            - "@twig"
            - "@oro_importexport.file.file_manager"
            - '@oro_importexport.file_manager'
            - "@logger"

    dmkclub_basics.provider.privilege_category_provider:
        class: "%dmkclub_basics.provider.privilege_category_provider.class%"
        tags:
            - { name: oro_user.privilege_category}

    dmkclub_basics.utility.datagrids:
        class: "%dmkclub_basics.utility.datagrids.class%"
        public: true
### Job Services
    dmkclub_basics.async.pdf.exportpdfsprocessor:
        class: 'DMKClub\Bundle\BasicsBundle\Async\Pdf\ExportPdfsMessageProcessor'
        arguments:
            - "@oro_message_queue.message_producer"
            - '@oro_message_queue.job.runner'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    dmkclub_basics.async.pdf.exportpdfprocessor:
        class: 'DMKClub\Bundle\BasicsBundle\Async\Pdf\ExportPdfProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - "@doctrine.orm.entity_manager"
            - '@DMKClub\Bundle\BasicsBundle\PDF\Manager'
            - "@knp_gaufrette.filesystem_map"
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
