parameters:
    dmkclub_basics.twigtemplate.entity.class:    DMKClub\Bundle\BasicsBundle\Entity\TwigTemplate
#    dmkclub_basics.twigtemplate.manager.class:   DMKClub\Bundle\BasicsBundle\Entity\Manager\TwigTemplateManager
    dmkclub_basics.pdf.manager.class:            DMKClub\Bundle\BasicsBundle\PDF\Manager
    dmkclub_basics.provider.privilege_category_provider.class: DMKClub\Bundle\BasicsBundle\Provider\PrivilegeCategoryProvider
    dmkclub_basics.utility.datagrids.class:      DMKClub\Bundle\BasicsBundle\Utility\Datagrids

    dmkclub_basics.datagrid.extension.totals.class:  DMKClub\Bundle\BasicsBundle\DataGrid\Extension\Totals\OrmTotalsExtension

services:

    oro_datagrid.extension.totals:
        class: "%dmkclub_basics.datagrid.extension.totals.class%"
        arguments:
            - '@translator'
            - '@oro_locale.formatter.number'
            - '@oro_locale.formatter.date_time'
            - '@oro_security.acl_helper'
        tags:
            - { name: oro_datagrid.extension }

    dmkclub_basics.pdf.manager:
        class: "%dmkclub_basics.pdf.manager.class%"
        arguments:
            - "@white_october.tcpdf"
            - "@twig"
            - "@oro_importexport.file.file_manager"
            - "@logger"

    dmkclub_basics.provider.privilege_category_provider:
        class: "%dmkclub_basics.provider.privilege_category_provider.class%"
        tags:
            - { name: oro_user.privilege_category}

    dmkclub_basics.utility.datagrids:
        class: "%dmkclub_basics.utility.datagrids.class%"
### Job Services
    dmkclub_basics.async.pdf.exportpdfsprocessor:
        class: 'DMKClub\Bundle\BasicsBundle\Async\Pdf\ExportPdfsMessageProcessor'
        arguments:
            - "@oro_message_queue.message_producer"
            - '@oro_message_queue.job.runner'
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    dmkclub_basics.async.pdf.exportpdfprocessor:
        class: 'DMKClub\Bundle\BasicsBundle\Async\Pdf\ExportPdfProcessor'
        arguments:
            - '@oro_message_queue.job.runner'
            - "@doctrine.orm.entity_manager"
            - "@dmkclub_basics.pdf.manager"
            - "@knp_gaufrette.filesystem_map"
            - "@logger"
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
