parameters:
    dmkclub_basics.twigtemplate.entity.class:            DMKClub\Bundle\BasicsBundle\Entity\TwigTemplate
#    dmkclub_basics.twigtemplate.manager.class:           DMKClub\Bundle\BasicsBundle\Entity\Manager\TwigTemplateManager
    dmkclub_basics.pdf.manager.class:            DMKClub\Bundle\BasicsBundle\PDF\Manager
services:
    dmkclub_basics.pdf.manager:
        class: "%dmkclub_basics.pdf.manager.class%"
        arguments:
            - "@white_october.tcpdf"
            - "@twig"
