datagrids:
# ###
# MemberBilling base grid
# ###
    dmkclub-memberbillings-grid:
        extended_entity_name: "%dmkclub_member.memberbilling.entity.class%"
        acl_resource: dmkclub_memberbilling_view
        source:
            type: orm
            query:
                select:
                    - mb.id
                    - mb.name
                    - mb.sign
                    - mb.feeTotal/100 As feeTotal
                    - mb.startDate
                    - mb.endDate
                    - mb.createdAt
                    - mb.updatedAt
                from:
                    - { table: "%dmkclub_member.memberbilling.entity.class%", alias: mb }
        columns:
            name:
                label:         dmkclub.member.memberbilling.name.label
            sign:
                label:         dmkclub.member.memberbilling.sign.label
            feeTotal:
                label:         dmkclub.member.memberbilling.fee_total.label
                frontend_type: currency
            startDate:
                label:         dmkclub.member.memberbilling.start_date.label
                frontend_type: date
            endDate:
                label:         dmkclub.member.memberbilling.end_date.label
                frontend_type: date
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      dmkclub_memberbilling_view
                params:     [ id ]
            update_link:
                type:       url
                route:      dmkclub_memberbilling_update
                params:     [ id ]
        sorters:
            columns:
                name:
                    data_name: mb.name
                sign:
                    data_name: mb.sign
                feeTotal:
                    data_name: mb.feeTotal
                startDate:
                    data_name: mb.startDate
                endDate:
                    data_name: mb.endDate
                createdAt:
                    data_name: mb.createdAt
                updatedAt:
                    data_name: mb.updatedAt
            default:
                endDate:  DESC
        filters:
            columns:
                name:
                    type: string
                    data_name: mb.name
                sign:
                    type: string
                    data_name: mb.sign
                    enabled: false
                feeTotal:
                    type: number
                    data_name: mb.feeTotal
                startDate:
                    type:      date
                    data_name: mb.startDate
                endDate:
                    type:      date
                    data_name: mb.endDate
                createdAt:
                    type:      datetime
                    data_name: mb.createdAt
                updatedAt:
                    type:      datetime
                    data_name: mb.updatedAt
                    enabled: false
            default:
                status: { value: 'active', type: Oro\Bundle\FilterBundle\Form\Type\TextFilterType::TYPE_EQUAL }
        actions:
            view:
                type: navigate
                acl_resource: dmkclub_memberbilling_view
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: dmkclub_memberbilling_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
