navigation:
    menu_config:
        items:
            dmkclub_sponsor:
                label:   'dmkclub.sponsor.entity_plural_label'
                route:   'dmkclub_sponsor_index'
                display: false
                extras:
                    routes:      ['/^dmkclub_sponsor_(index|view)$/']
                    position:    200
                    description: 'dmkclub.sponsor.entity_plural_label'
    
        tree:
            application_menu:
                children:
                    customers_tab:
                        children:
                            dmkclub_sponsor: ~
    
    titles:
        dmkclub_sponsor_index: ~
        dmkclub_sponsor_view:  '%sponsor.name%'
        dmkclub_sponsor_create: 'Create Sponsor'
        dmkclub_sponsor_update: '%sponsor.name% - Edit'
        dmkclub_sponsorcategory_create: 'Create Category'
        dmkclub_sponsorcategory_update: '%sponsorcategory.name% - Edit'
    