parameters:

services:
    dmkclub.sponsor.form.type:
        class: DMKClub\Bundle\SponsorBundle\Form\Type\SponsorType
        arguments:
            - "@translator"
        tags:
            - { name: form.type, alias: dmkclub_sponsor_sponsor }

    dmkclub.sponsor.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_sponsor_sponsor"
            - DMKClub\Bundle\SponsorBundle\Form\Type\SponsorType
            - null
            
    dmkclub.sponsor.form.handler:
        class: DMKClub\Bundle\SponsorBundle\Form\Handler\SponsorHandler
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: oro_tag.tag_manager }

    dmkclub.sponsorcategory.form.type:
        class: DMKClub\Bundle\SponsorBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: dmkclub_sponsor_category }

    dmkclub.sponsorcategory.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_sponsor_category"
            - DMKClub\Bundle\SponsorBundle\Form\Type\CategoryType
            - null

    dmkclub.sponsorcategory.form.handler:
        class: DMKClub\Bundle\SponsorBundle\Form\Handler\CategoryHandler
        arguments:
            - '@doctrine.orm.entity_manager'

# ####
# FormWidgets
# ####

    # Form SELECT type
    dmkclub_sponsor.form.type.category_select:
        class: DMKClub\Bundle\SponsorBundle\Form\Type\CategorySelectType
        tags:
            - { name: form.type, alias: dmkclub_sponsorcategory_select }
