DMKClub\Bundle\SponsorBundle\Entity\Sponsor:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        contact:
            - NotBlank: ~
        account:
            - NotBlank: ~
