datagrids:
# ###
# MemberBilling base grid
# ###
    dmkclub-basics-twigtemplate-grid:
        extended_entity_name: "%dmkclub_basics.twigtemplate.entity.class%"
        acl_resource: dmkclub_basics_twigtemplate_view
        source:
            type: orm
            query:
                select:
                    - t.id
                    - t.name
                    - t.createdAt
                    - t.updatedAt
                from:
                    - { table: "%dmkclub_basics.twigtemplate.entity.class%", alias: t }
        columns:
            name:
                label:         dmkclub.basics.twigtemplate.name.label
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      dmkclub_basics_twigtemplate_view
                params:     [ id ]
            update_link:
                type:       url
                route:      dmkclub_basics_twigtemplate_update
                params:     [ id ]
        sorters:
            columns:
                name:
                    data_name: t.name
                createdAt:
                    data_name: t.createdAt
                updatedAt:
                    data_name: t.updatedAt
            default:
                name:  ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: t.name
                createdAt:
                    type:      datetime
                    data_name: t.createdAt
                updatedAt:
                    type:      datetime
                    data_name: t.updatedAt
                    enabled: false
            default:
                status: { value: 'active', type: Oro\Bundle\FilterBundle\Form\Type\TextFilterType::TYPE_EQUAL } 
        actions:
            view:
                type: navigate
                acl_resource: dmkclub_basics_twigtemplate_view
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: dmkclub_basics_twigtemplate_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
