oro_entity:
    virtual_fields:
        DMKClub\Bundle\MemberBundle\Entity\Member:
            # used for marketing list. There must be a method getPrimaryEmail in Entity as well used by EmailCampaign!
            primaryEmail:
                query:
                    select:
                        expr:         e.email
                        return_type:  string
                    join:
                        left:
                            - { join: 'OroContactBundle:ContactEmail', alias: e, conditionType: 'WITH', condition: 'e.owner = entity.contact and e.primary = true' }
            contactInformation:
                query:
                    select:
                        expr:         e.email
                        return_type:  string
                    join:
                        left:
                            - { join: 'OroContactBundle:ContactEmail', alias: e, conditionType: 'WITH', condition: 'e.owner = entity.contact and e.primary = true' }
