dmkclub_member_bundle_member_api:
    resource:     "@DMKClubMemberBundle/Controller/Api/Rest/MemberController.php"
    type:         rest
dmkclub_member_bundle_memberfeediscount_api:
    resource:     "@DMKClubMemberBundle/Controller/Api/Rest/MemberFeeDiscountController.php"
    type:     rest
dmkclub_member_bundle_memberfee_api:
    resource:     "@DMKClubMemberBundle/Controller/Api/Rest/MemberFeeController.php"
    type:     rest
    