search:
    DMKClub\Bundle\MemberBundle\Entity\Member:
        alias:                          dmkclub_member
        label:                          dmkclub.member.entity_plural_label
        title_fields:                   [firstName, lastName]
        route:
            name:                       dmkclub_member_view
            parameters:
                id:                     id
        search_template:                DMKClubMemberBundle:Member:searchResult.html.twig
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   member_code
                target_type:            text
                target_fields:          [memberCode]
            -
                name:                  dataChannel
                relation_type:         many-to-one
                relation_fields:
                    -
                        name:          id
                        target_type:   integer
                        target_fields: [dataChannelId]

    DMKClub\Bundle\MemberBundle\Entity\MemberProposal:
        alias:                          dmkclub_member_proposal
        label:                          dmkclub.member_proposal.entity_plural_label
        title_fields:                   [firstName, lastName]
        route:
            name:                       dmkclub_member_proposal_view
            parameters:
                id:                     id
        search_template:                DMKClubMemberBundle:MemberProposal:searchResult.html.twig
        fields:
            -
                name:                   lastName
                target_type:            text
                target_fields:          [lastName]
            -
                name:                   firstName
                target_type:            text
                target_fields:          [firstName]
            -
                name:                   emailAddress
                target_type:            text
                target_fields:          [emailAddress]
            -
                name:                   phone
                target_type:            text
                target_fields:          [phone]
            -
                name:                   comment
                target_type:            text
                target_fields:          [comment]
