datagrids:
    dmkclub-sepacreditor-grid:
        extended_entity_name: "%dmkclub.payment.sepacreditor.entity.class%"
        acl_resource: dmkclub_sepacreditor_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.name
                    - c.iban
                    - c.bic
                    - c.creditorId
                    - c.created
                    - c.updated
                from:
                    - { table: "%dmkclub.payment.sepacreditor.entity.class%", alias: c }
        columns:
            name:
                label:         dmkclub.payment.sepacreditor.name.label
            iban:
                label:         dmkclub.payment.sepacreditor.iban.label
            bic:
                label:         dmkclub.payment.sepacreditor.bic.label
            creditorId:
                label:         dmkclub.payment.sepacreditor.creditor_id.label
            created:
                label:         oro.ui.created_at
                frontend_type: datetime
                renderable:    false
            updated:
                label:         oro.ui.updated_at
                frontend_type: datetime
                renderable:    false
        properties:
            id: ~
            update_link:
                type:       url
                route:      dmkclub_sepacreditor_update
                params:     [ id ]
            delete_link:
                type: url
                route: dmkclub_api_delete_sepacreditor
                params: [ id ]
        actions:
            delete:
                type:         delete
                acl_resource: dmkclub_member_sepacreditor_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
            update:
                type: dialog
                label: oro.grid.action.update
                icon: edit
                link: update_link
                widgetOptions:
                    reload-grid-name: dmkclub-sepacreditor-grid
                    options:
                        dialogOptions:
                            title:  "@translator->trans(dmkclub.payment.sepacreditor.entity_label)"
                            modal:  true
                            allowMaximize: true
                            allowMinimize: false
                            dblclick: maximize
                            maximizedHeightDecreaseBy: minimize-bar
                            width:  700
