navigation:
    menu_config:
        items:
            accounting_tab:
                label: 'accounting'
                uri: '#'
                display: false
                extras:
                    icon: fa-money
                    position: 11
