dmkclub_payment_bundle:
    resource:     "@DMKClubPaymentBundle/Controller"
    type:         annotation
    prefix:       /dmkclub
    options:
        expose: true


dmkclub_payment_bundle_api:
    resource: "@DMKClubPaymentBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
