parameters:
#    dmkclub.prcontact.form.type.api.class: DMKClub\Bundle\PublicRelationBundle\Form\Type\PRContactApiType
#    dmkclub.form.type.prcontact_select.class:        DMKClub\Bundle\PublicRelationBundle\Form\Type\PRContactSelectType

services:
    dmkclub.prcontact.form.type:
        class: DMKClub\Bundle\PublicRelationBundle\Form\Type\PRContactType
        tags:
            - { name: form.type, alias: dmkclub_prcontact }

#    dmkclub.prcontact.form.type.api:
#        class: "%dmkclub.prcontact.form.type.api.class%"
#        tags:
#            - { name: form.type, alias: dmkclub_prcontact_api }

    dmkclub.prcontact.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "dmkclub_prcontact"
            - DMKClub\Bundle\PublicRelationBundle\Form\Type\PRContactType
            - null

#    dmkclub.prcontact.form.api:
#        class: Symfony\Component\Form\Form
#        factory: ['@form.factory', createNamed]
#        arguments:
#            - "prcontact"
#            - "dmkclub_prcontact_api"

    dmkclub.prcontact.form.handler:
        class: DMKClub\Bundle\PublicRelationBundle\Form\Handler\PRContactHandler
        arguments:
            - "@doctrine.orm.entity_manager"

#    dmkclub.prcontact.form.handler.api:
#        class: %dmkclub.prcontact.form.handler.class%
#        arguments:
#            - @dmkclub.prcontact.form.api
#            - @request
#            - @doctrine.orm.entity_manager

#    dmkclub.form.type.prcontact_select:
#        class: %dmkclub.form.type.prcontact_select.class%
#        tags:
#            - { name: form.type, alias: "dmkclub_prcontact_select" }
