parameters:
    dmkclub.prcontact.entity.class: DMKClub\Bundle\PublicRelationBundle\Entity\PRContact
    dmkclub.prcategory.entity.class:       DMKClub\Bundle\PublicRelationBundle\Entity\PRCategory

services:
#    dmk_club_public_relation.example:
#        class: %dmk_club_public_relation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
